### ISSUE TITLE
Examples not working 

### ISSUE THREAD

**Issue by g-javi** [rei-vilo/SD_TM4C#2]
Are the examples here updated? I'm trying to use it on TM4C123 but can't get them working.

**Comment by rei-vilo** [comment]
Could you please be more specific?

**Comment by g-javi** [comment]
@rei-vilo Thanks for your reply, I'm testing the Datalogger (under the examples directory) but I can't manage to get it to work, do I need to modify the a file for pin mapping?

**Comment by g-javi** [comment]
Update: @rei-vilo don't worry about it, I was using the wrong pin! Thanks for your reply!
